### ISSUE TITLE
Per Route Rate Limit

### ISSUE THREAD

**Issue by csprance** [fastify/fastify-rate-limit#10]
Is it possible to use this rate-limiter per route instead of for every route?

**Comment by delvedor** [comment]
Currently not, but from Fastify v2 this module will need a refactor and we can think about adding that feature :)

**Comment by poppinlp** [comment]
+1
This is really a necessary feature. 👍

**Comment by leonidas-120** [comment]
Any updates on this?? Its a really useful feature !!

**Comment by cemremengu** [comment]
@mcollina @delvedor I am thinking a list of paths (or pattern matchers?) called `only` can be provided via opts. If the list is `undefined` rate limit will be applied to all routes. What do you think about this approach?

**Comment by mcollina** [comment]
+1, that would work.

**Comment by matth-c3** [comment]
Hello, 

Any update by any chance ? 

Thanks

**Comment by mcollina** [comment]
It seems a very popular feature that needs a proper solution. I'll write my thoughts on this one, as an alternative implementation to https://github.com/fastify/fastify-rate-limit/pull/22.

It is possible to implement this in this way:

```js
app.get('/some/route', {
  config: {
   rateLimit: {
    max: 1000
  }
})
```

How? You can use that config to change the option passed into a route:

```js
app.addHook('onRoute', (routeOptions) => {
  if (routeOptions.rateLimit) {
    // do something!
    // as an example, add a custom hook
    // routeOptions.preHandler = ...
  }
})
```
