### ISSUE TITLE
route level whitelist do not work

### ISSUE THREAD

**Issue by donghc** [fastify/fastify-rate-limit#113]
## 🐛 Bug Report

When routing level whitelist is used, it does not take effect

## To Reproduce

```
fastify.get('/private', {
  config: {
    rateLimit: {
      max: 3,
      whitelist: ['127.0.0.1', '127.0.3.1'],
      timeWindow: '1 minute'
    }
  }
}, (req, reply) => {
  reply.send({ hello: 'from ... private' })
})
```

## Your Environment

- *node version*: v14.4.0
- *fastify version*: ^3.8.0
- *os*: Mac
- *any other relevant information*

**Comment by Sven65** [comment]
This is still an issue.
