### ISSUE TITLE
rename whitelist to allowedClient

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-rate-limit#114]
## 🚀 Feature Proposal

Rename the `whitelist` option to `allowedClient`
This will be a breaking change.

## Motivation

This wording is more inclusive.

**Comment by kibertoad** [comment]
Why not go with deprecation first?

**Comment by Eomm** [comment]
I think it would be easy to manage this change for users and it would take less work for us on next fastify major (that is already a lot of work)

For sure we can do as you suggested tho

**Comment by mcollina** [comment]
I would recommend supporting both and only documenting allowlist or passlist. I'm not fond of "allowedClients".

**Comment by hidekysilva** [comment]
The PR for this issue was merged. Here's the link, in case someone wants to link it to this issue.
https://github.com/fastify/fastify-rate-limit/pull/117
