### ISSUE TITLE
Return an error object instead of a POJO.

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify-rate-limit#121]
Currently, we are returning a POJO (and using a custom serializer) instead of an error object, which means that the `.setErrorHandler` API won't be called.
This should be considered a bug, as users can't override the default response nor perform custom actions when a 429 error happens.

**Comment by mcollina** [comment]
Creating a new `Error` used to be somewhat _expensive_ and while things have improved, it's still slower than using FJS. I'm ok with this change as it improve functionality for our end users, but I think it should be semver-major.
