### ISSUE TITLE
Rate limit 404s

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-rate-limit#127]
## 🚀 Feature Proposal

It would be interesting to rate limit 404s as well. This might be controversial because it's faster to actually return a 404 vs read up the current limit from a database. However it might be a security risk as an attacker could search which routes are available.

## Example

```js
  const fastify = Fastify()
  await fastify.register(rateLimit, { global: true, max: 2, timeWindow: 1000 })
  fastify.setNotFoundHandler({
    onRequest: fastify.rateLimit
  }, function (request, reply) {
    reply.code(404).send({ hello: 'world' })
  })
  fastify.get('/', function (request, reply) {
    reply.send({ hello: 'world' })
  })
  await fastify.listen(3000)
```

**Comment by jsumners** [comment]
Sounds good to me.

**Comment by nherment** [comment]
I would appreciate any tips to send a PR on this.

After looking at the fastify docs on error handling an ideal solution is not obvious.

Is it possible with fastify to add a hook around the notFoundHandler and still allow users to customize the handler?

**Comment by mcollina** [comment]
You should expose https://github.com/fastify/fastify-rate-limit/blob/4856e340ceb6d0c22663bc47cf3dced8dd74a3df/index.js#L139 via `fastify.decorate('rateLimit')`, then the snippet above will work.

(We also need documentation)
