### ISSUE TITLE
PR #123 is preventing use cases of multiple rate limiter usage

### ISSUE THREAD

**Issue by squareloop1** [fastify/fastify-rate-limit#129]
## 💥 Regression Report

Since PR #123 it is not possible to register two rate limiter like for a use case where a global rate limiter should be applied and a second, stricter limiter to only some specific routes like this (nestjs registration of the rate limiter):

```TS
    // rate limiter for every route except /auth/password
    await app.register(fastifyRateLimit, {
      max: 150,
      timeWindow: 1000 * 60 * 5, // 150 req/5min
      redis: new Redis({ ...configService.redisConnectionData, keyPrefix: 'ratelimit:' }),
      whitelist: (req) => {
        return req.url === '/auth/password';
      },
      errorResponseBuilder: rateLimitErrorResponse,
    });

    // rate limiter for /auth/password route only
    await app.register(fastifyRateLimit, {
      max: 15,
      timeWindow: 1000 * 60 * 5, // 15 req/5min
      redis: new Redis({ ...configService.redisConnectionData, keyPrefix: 'ratelimit:auth:' }),
      whitelist: (req) => {
        return req.url !== '/auth/password';
      },
      errorResponseBuilder: rateLimitErrorResponse,
    });
```

## Last working version

Worked up to version: 5.0.0

Stopped working in version: 5.0.1

## To Reproduce

Use two rate limiters, the second one registered does not work.

## Expected behavior

Multiple rate limiter should be usable for a use case where a stricter rate limiting is needed for some routes.

## Your Environment

- *node version*: 14
- *fastify version*: >3.0.0
- *os*: WSL2

**Comment by mcollina** [comment]
Would you like to send a PR to fix? You'll need to move the symbol definition inside the plugin function.
