### ISSUE TITLE
Per-route ratelimits don't work.

### ISSUE THREAD

**Issue by Sven65** [fastify/fastify-rate-limit#148]
## 🐛 Bug Report

As described in #113, using a per-route ratelimit doesn't work.

## To Reproduce

1. Create a new fastify instance
2. Register the ratelimit plugin
3. Add a ratelimit on a specific route

```ts
import fastify, { FastifyInstance, FastifyRequest } from 'fastify'

import ratelimit from 'fastify-rate-limit'

const server: FastifyInstance = fastify()

server.register(ratelimit,{
	global: false,
	max: 3000,
	keyGenerator: (req: FastifyRequest): string => {
		return req.headers.authorization
	},
})

server.get('/private', {
	config: {
	  rateLimit: {
		max: 3,
		timeWindow: '1 minute'
	  }
	}
  }, (req, reply) => {
	reply.send({ hello: 'from ... private' })
})
```

## Expected behavior

I expect the ratelimit to be applied.

## Your Environment

- *node version*: 14.16.0
- *fastify version*: ^3.14.12
- *fastifi-ratelimit version*: ^5.5.0
- *os*: Mac
- *any other relevant information*

**Comment by Eomm** [comment]
This test cover this use case:

https://github.com/fastify/fastify-rate-limit/blob/b8bd78929c0bb4c32d83544f4d2e5c4d09cd330c/test/route-rate-limit.test.js#L22

Would you mind debugging this issue?
Maybe is the `keyGenerator` that is in conflicts with the rate-limit usage? Did you try to return a static string?

**Comment by Sven65** [comment]
If I return a static string, it still doesn't work. I have other plugins register before the ratelimit as well, but the `onRequest` hook of those register the `rateLimit` config option properly.

**Comment by Sven65** [comment]
After some testing, it seems the issue is with the `onRoute` hook not being fired for my routes, as they are loaded dynamically by another plugin, and the issue seems to be with that one.

**Comment by Sven65** [comment]
Tested using `.after()` to register the ratelimit plugin, and it unfortunately turns out to still not be working.

The way I originally tested was to write my own plugin that just logged the registered routes. As they didn't log the ones registered from the [loader plugin](https://github.com/L2jLiga/fastify-decorators/blob/v3/docs/Bootstrapping.md), I added a `.after()` hook to it and tried to register the plugin again, inside that callback, which logged all the routes with the `rateLimit` configs.

Doing the same, but swapping back to the `fastify-rate-limit` plugin, I still experience the same issue where it doesn't register properly, and no ratelimit is applied.

I'd be glad to provide more details and examples if needed, just give me a ping :)

**Comment by Eomm** [comment]
> I'd be glad to provide more details and examples if needed, just give me a ping :)

Yes, it is not clear your setup - if there is a bug this would be helpful, because to read the `rateLimit` config I would use the `onRoute` hook and not the `.after()` method tho

**Comment by Sven65** [comment]
It seems that it does in fact work with per-route configs, and that I just wasn't registering the plugin correctly.

As it turns out, not only was I registering the plugin **after** my routes, but I also didn't wait for it to finish registering.

Thanks for the help with my issue!
