### ISSUE TITLE
🐛 Bug Report # Redis expire not working

### ISSUE THREAD

**Issue by aligzl** [fastify/fastify-rate-limit#152]
I setup redis on rate-limit options, but it does not sets TTL ( expire )

- *node version*: 16
- *fastify version*: >=3.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Can you add an example to reproduce?

**Comment by aligzl** [comment]
It creates key in redis without TTL ( -1 ), so it doesnt expire and blocks  permanently ( see image link below)
```
const fastify = require('fastify')({
  logger: {
    level: 'info' // Will use pino.destination()
  }
});
const crypto                = require('crypto');
const redis = require('./init-redis')
fastify.register(require('fastify-rate-limit'), {
  /* ... */
  
  keyGenerator: function(req) {
    return req.user ? req.user.username : crypto.createHash('md5').update(req.headers['ip'] || 'unknown' + req.headers['user-agent'] || 'unknown').digest('hex')
  },
  skipOnError: true,
  redis,
  global: true, max: 100, timeWindow: '1 minute'
})
```

[https://imgur.com/gUuWgmH](url)

**Comment by mcollina** [comment]
As you can see in https://github.com/fastify/fastify-rate-limit/blob/master/store/RedisStore.js, we are calling pexpire.

Please include a runnable example to reproduce your problem (something I can run with node file.js). I'd also be very happy if you could send a PR fixing this.

**Comment by tabz24** [comment]
@aligzl I experienced the same thing and it worked for after I passed the time in ms as an integer instead of a string.
