### ISSUE TITLE
Headers are added even when set to false

### ISSUE THREAD

**Issue by TheTimmaeh** [fastify/fastify-rate-limit#166]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.1

### Plugin version

5.5.0

### Node.js version

14.15.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Headers like 'x-ratelimit-limit' are always added to the response when the limit has not yet been exceeded, as seen here: https://github.com/fastify/fastify-rate-limit/blob/b8bd78929c0bb4c32d83544f4d2e5c4d09cd330c/index.js#L206-L209

### Steps to Reproduce

1. Implement fastify-rate-limit
2. Set low 'max' and high 'timeWindow' values
3. Set specific headers to 'false'
4. Request a route

### Expected Behavior

If set to false, those headers should **never** be added, no matter whether the limit has been exceeded or not. Or there should be an option to enforce this behaviour.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
I agree, the option should work in that case.

**Comment by TheTimmaeh** [comment]
I've implemented it the same way as addHeaders.
