### ISSUE TITLE
Wrong type for max function in RateLimitOptions

### ISSUE THREAD

**Issue by leonitousconforti** [fastify/fastify-rate-limit#176]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.1

### Plugin version

5.5.0

### Node.js version

16.6.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Big Sur 11.4

### Description

The docs page states that the max function `can be an async function with the signature async (req, key) => {} where req is the Fastify request object and key is the value generated by the keyGenerator. The function must return a number.`

However, typescript complains I have the wrong type when I use an async function because Promise<number> is not assignable to number. 

Basically, I think the type definition for the max function needs to be changed from:

```js
number | ((req: FastifyRequest, key: string) => number)
```

to:

```js
number | ((req: FastifyRequest, key: string) => number) | ((req: FastifyRequest, key: string) => Promise<number>)
```

### Steps to Reproduce

```js
// Declare a config object
const config: RateLimitPluginOptions = {
    ban: 10,
    timeWindow: '2 minute',
    store: new Redis(process.env.REDIS_URL, { connectTimeout: 500, maxRetriesPerRequest: 1 }) as any,
    keyGenerator: function (req) {
        return req.headers['authorization'] || req.ip;
    },

    // This is where the error is
    async max(request, key) {
        const apiKeyObject = await ApiKey.findOne({ where: { apiKey: key } });
        if (!apiKeyObject) {
            return 10;
        }

        return apiKeyObject.rateLimit;
    }
};

// Register the plugin
app.register(fastifyRateLimit, config);
```

The exact error is:
```
Type '(request: FastifyRequest<RouteGenericInterface, Server, IncomingMessage>, key: string) => Promise<number>' is not assignable to type '(req: FastifyRequest<RouteGenericInterface, Server, IncomingMessage>, key: string) => number'.
    Type 'Promise<number>' is not assignable to type 'number'.
```

**Comment by leonitousconforti** [comment]
I can see there is async support in the Library, but it's just missing from the types

https://github.com/fastify/fastify-rate-limit/blob/ce1d4e1ef12ba7d784d74655952fe08e79f43fed/index.js#L202-L208

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by leonitousconforti** [comment]
Yup, all done. Just wasn't sure if you wanted a pull request for such a minor change
