### ISSUE TITLE
allowList not working in Endpoint config

### ISSUE THREAD

**Issue by petef19** [fastify/fastify-rate-limit#178]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

5.6.1

### Node.js version

14.6.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10 x64

### Description

Read the docs and the examples, they're pretty clear IMO. I must be missing something.
I cannot get `allowList` to work in the config for an `endpoint`. It does work though when used in the `global` config.

### Steps to Reproduce

This works for allowing `127.0.0.1` - via global config:
```
fastify.register(fastifyRateLimit,
    {
        global: false,
        max: 3000, // default max rate limit
        allowList: ['127.0.0.1'], // global allowList access ( ACL based on the key from the keyGenerator)
        skipOnError: false, // default false
    });
```

But, when I'm specifying `127.0.0.1` in the `allowList` directly for an `endpoint`, it does not kick in:
```
fastify.route({
        url: '/activate',
        method: 'POST',
        schema: {},
        handler: (request) => {
            return rt_activate(request);
        },
        config: {
            rateLimit: {
                max: 3,
                timeWindow: '1 minute',
                allowList: ['127.0.0.1'],     // <--------- never kicks in
                errorResponseBuilder: (req: FastifyRequest, context: any) =>
                    ({
                        code: 429, timeWindow: context.after, limit: context.max,
                        message: 'Too many requests sent. Please try again in 1 minute.'
                    }),
                onExceeding: function(req: FastifyRequest){
                    console.log('callback on exceeding ... executed before response to client. req is give as argument')
                },
                onExceeded: function(req: FastifyRequest){
                    console.log('callback on exceeded ... to block ip in security group for example, req is give as argument')
                }
            }
        }
    }
);
```

What am I doing wrong ?

### Expected Behavior

to white list / allow the specified IPs in the `endpoint config > allowList array`.

Thanks.

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by petef19** [comment]
@Eomm 
> No, I think it should work since the `makeParams` function in the code should configure this setting for the route you are declaring.

well, it does NOT work as per my example above on latest version...  ;-)  so, is my code incorrect ?

As explained, when I remove `allowList` in the `global` config and just use it in the route based config, it does NOT kick in....

**Comment by rluvaton** [comment]
#216 merged, I think we should close this issue
