### ISSUE TITLE
Does redis store do atomic increments?

### ISSUE THREAD

**Issue by TarasKalynii** [fastify/fastify-rate-limit#189]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Does Redis store use atomic increments, I mean that is all operations in memory, or distributed environment use atomic increments against race conditions?

**Comment by Eomm** [comment]
Redis is a single-threaded store so it does not deal with race conditions, the increments are executed in serial.
