### ISSUE TITLE
More efficient limiting

### ISSUE THREAD

**Issue by vader-sama** [fastify/fastify-rate-limit#191]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### Description

I ​think the current rate limiter is missing the point. Rate limiters are made to prevent brute force attacks, right?
The thing is, `fastify-rate-limiter` only blocks **most** of brute force requests.
Let me give you an example:
I've reached the limit and now I'm locked for 2 minutes. I'll wait for 1 minute and will send a request to the server again.
It will says that *I should wait for 1 more minute*.

Nothing wrong right? 🧐

But imagine a script; which will send 15 requests to the server every minute. It will reach the rate limit after 1 minute (lets assume limit is at `15` and lock time is `2m`). It will keep sending requests until the rate limit ends. after that it will send another 15 requests to the server. so its sending 15 requests every 3 minute even when rate limiter is on!

###  Solution
I think the best solution is to renew the lock time on every request when the ip is locked

### Motivation

I've discovered `Fastify` recently, and since then I'm in love with it 😁 

I try to use `Fastify` version  of everything when I'm developing using `Fastify`! Rate limiter is one of those. Maybe the feature that I'm requesting is not useful But I needed it, so I shared my thoughts with you guys.

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this feature? Remember to add unit tests.

I think the `onExceeding` function could be improved to support this

**Comment by vader-sama** [comment]
@Eomm Sure why not
I'll look into this at weekend
Thanks for the response! 🙏🤩

**Comment by jsumners** [comment]
I wonder how others handle this. For example, if you exceed the limit on the GitHub API, do they extend you by another hour every time you accidentally hit the API when you're over the limit? I think there is some sort of windowing that must happen.

**Comment by vader-sama** [comment]
@jsumners I believe time limits are mostly short and usually in minutes. Because locking someone for an hour doesn't make sense; But that's a good point tho. Making it dynamic is definitely much better, but How? I mean what's the scenario?

**Comment by jsumners** [comment]
I don't have an answer except to say the logic for extending the ban should be modular such that it can be replaced by user desired logic.

**Comment by vader-sama** [comment]
@jsumners We can get a boolean value from the user for it, and add more strategies in the future

**Comment by vader-sama** [comment]
Was added in 67b4247a6da33df7d80146de7fa53707c1a07c2a
