### ISSUE TITLE
Ignore certain status codes

### ISSUE THREAD

**Issue by Emiliaaah** [fastify/fastify-rate-limit#201]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'd like to be able to set different rate limits based on the status code that is returned.
(I wouldn't mind implementing this feature myself if it isn't to hard to implement)

### Motivation

I'm currently working on a project that relies on a feature like this.

### Example

I'll just use my current project as an example. I have an endpoint that provides some data this data can be public or private if this data is private the user will need to provide a password. To prevent users from just brute forcing passwords I'd like to rate limit the ability to authenticate but without affecting normal usage.

**Comment by mcollina** [comment]
Go for it!

**Comment by Emiliaaah** [comment]
I do have an idea which might work so I'd love your insight on this and what you think about it. So my idea is to add some sort of function which you can call to increment the requests the user has send, because from my understanding the rate limiting is handled before the handler gets run which makes total sense but since you don't know what status code you're gonna get before the actual code is run you can't really do this. This function would solve this problem since you would call it once you know what the status code is gonna be.

I'm just writing down my thoughts, and I'd have to take a look through the code base to see how viable this option would be.
Since you're more familiar with the code base than I am I'd love your thoughts on this implementation and if there might be a better way to do this than what I just explained.

**Comment by mcollina** [comment]
go for it!
