### ISSUE TITLE
Clarifying usage of `continueExceeding` option

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-rate-limit#206]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hopefully @vader-sama can answer this if he's not too busy crushing rebels!

My understanding is that when `continueExceeding` is set to `true`, the following scenario will occur:

- User hits rate limit and is limited for a certain amount of time (say 60 seconds)
- If the user makes another request between the time they were rate-limited and the time their rate-limit was due to expire, then it is reset back to 60 seconds

Is this correct?

Just wanted to make sure I understand its usage before I file a bug report that may not be needed.

**Comment by vader-sama** [comment]
Hi
Yeap, that's pretty much it
