### ISSUE TITLE
`continueExceeding` option does not reset rate-limit

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-rate-limit#207]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

5.7.0

### Node.js version

16.14.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Restating what was said in https://github.com/fastify/fastify-rate-limit/issues/206:

My understanding is that when `continueExceeding` is set to `true`, the following scenario will occur:

- User hits rate limit and is limited for a certain amount of time (say 60 seconds)
- If the user makes another request between the time they were rate-limited and the time their rate-limit was due to expire, then it is reset back to 60 seconds

However, this does not appear to be the case when testing, and the rate-limit is not reset.

### Steps to Reproduce

1. Stand up Fastify server:

```js
const fastify = require("fastify")({ logger: true });

// Import plugins
const rateLimit = require("fastify-rate-limit");

/**
 * @description test function
 */
async function server() {
	fastify.register(rateLimit, {
		max: 2,
		timeWindow: 10000,
		continueExceeding: true,
	});

	fastify.route({
		method: "GET",
		url: "/foo",
		handler: async (req, res) => {
			res.send("ok");
		},
	});
	await fastify.listen({ port: 8000 });
}

server();
```

2. Make GET request twice to trigger rate-limit:

```
Request:

> GET /foo HTTP/1.1
> Host: localhost:8000
> Accept: */*

Response:

< HTTP/1.1 200 OK
< x-ratelimit-limit: 2
< x-ratelimit-remaining: 1
< x-ratelimit-reset: 10
< content-type: text/plain; charset=utf-8
< content-length: 2
< Date: Wed, 09 Feb 2022 15:10:55 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

```
Request:

> GET /foo HTTP/1.1
> Host: localhost:8000
> Accept: */*

Response:

< HTTP/1.1 200 OK
< x-ratelimit-limit: 2
< x-ratelimit-remaining: 0
< x-ratelimit-reset: 9
< content-type: text/plain; charset=utf-8
< content-length: 2
< Date: Wed, 09 Feb 2022 15:10:56 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

3. Make GET request after hitting 2 request rate-limit:
```
Request:
> GET /foo HTTP/1.1
> Host: localhost:8000
> Accept: */*

Response:
< HTTP/1.1 429 Too Many Requests
< x-ratelimit-limit: 2
< x-ratelimit-remaining: 0
< x-ratelimit-reset: 8
< retry-after: 10000
< content-type: application/json; charset=utf-8
< content-length: 99
< Date: Wed, 09 Feb 2022 15:10:57 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```
4. Make GET request within 10 seconds after rate-limit triggered (still expecting to be denied access, as step 3. should have reset the rate-limit back to 10 seconds, so shouldn't have allowed access again until 15:11:07 GMT):

```
Request:
> GET /foo HTTP/1.1
> Host: localhost:8000
> Accept: */*

Response:
< HTTP/1.1 200 OK
< x-ratelimit-limit: 2
< x-ratelimit-remaining: 1
< x-ratelimit-reset: 10
< content-type: text/plain; charset=utf-8
< content-length: 2
< Date: Wed, 09 Feb 2022 15:11:01 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

### Expected Behavior

Rate-limit should be reset if user makes request between the time they were rate-limited and the time their rate-limit was due to expire if `continueExceeding` set to `true`.

**Comment by rluvaton** [comment]
Can I try and fix this?

**Comment by rluvaton** [comment]
I can confirm it's effecting MacOS 12.2

**Comment by rluvaton** [comment]
Just tested and there is no issue when using the Redis store
