### ISSUE TITLE
LocalStore behavior is different that RedisStore

### ISSUE THREAD

**Issue by rluvaton** [fastify/fastify-rate-limit#215]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

5.7.0

### Node.js version

16.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2

### Description
In the `LocalStore` the `timeWindow` **time**  (not the amount of requests a user can make) is shared for all the users and in the `RedisStore` each user has its own `timeWindow`

_Originally posted by @rluvaton in https://github.com/fastify/fastify-rate-limit/issues/208#issuecomment-1034169203_

### Steps to Reproduce

**when using the local store:**

Let's say the time window is 10s and the rate limit is 1 and `continueExceeding` is false
1. User 1: send a request (which internally starts the global interval) - ok
2. User 2: send a request after 7 seconds - ok
3. User 2: send another request again - rate limited
4. User 2: send another request after 5 seconds - not been rate-limited (which he should as 10 has not passed for him only 5)

From reading the Redis store code and testing it, each user has its own time window (meaning User 2 in step 4 would be rate-limited)

[Reproduction repo](https://github.com/rluvaton/fastify_fastify-rate-limit-repro-215) just follow the steps to run or scroll down to see the final result for me

### Expected Behavior

Both stores to have the same behavior

**Comment by rluvaton** [comment]
I've edited with the reproduction repo

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by rluvaton** [comment]
Sure, working on this, now 😄
