### ISSUE TITLE
Custom hook option

### ISSUE THREAD

**Issue by leomp12** [fastify/fastify-rate-limit#224]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add an option to use custom hook:

```js
{
  hook: 'preHandler', // default 'onRequest'
}
```

### Motivation

I have (and I think other people might have too) the exact opposite case mentioned here  https://github.com/fastify/fastify-rate-limit/issues/83 🥲 
I mean, **sometimes the need is to limit authenticated requests**, to count requests per tenant/authentication, rate limiting by IP (soft limits) is already done in the proxy (Imo it's also a good practice, right ?), so the `keyGenerator` for rate limit plugin must be called after other hooks that handle authentication.

### Example

```ts
import type { RateLimitPluginOptions } from 'fastify-rate-limit';

const rateLimitOptions: RateLimitPluginOptions = {
  hook: 'preHandler',
  max: 30,
  timeWindow: '1 minute',
  allowList: ['_'],
  keyGenerator(request) {
    if (request.isPermissionGranted) {
      return request.authenticationId;
    }
    return '_';
  },
};

export default rateLimitOptions;
```

**Comment by leomp12** [comment]
And I can give try if you want me to

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by leomp12** [comment]
@mcollina I wouldn't say I'd LIKE to send a PR  😆 
But yup, I can try it in the next few days 👍🏾
