### ISSUE TITLE
onExceeding / onExceeded not supported globally?

### ISSUE THREAD

**Issue by jstayton** [fastify/fastify-rate-limit#232]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey 👋🏻 

I tried using `onExceeding` and `onExceeded` globally, like this:

```js
fastify.register(import('fastify-rate-limit'), {
  max: 1,
  timeWindow: '1 minute',
  enableDraftSpec: true,
  onExceeding: function (request) {
    request.log.warn('onExceeding')
  },
  onExceeded: function (request) {
    request.log.warn('onExceeded')
  },
})
```

But neither function was ever called.

I then tried adding them to a specific route, and they started working. That's when I realized that the README doesn't actually mention either function in the options that can be set.

So, all of that to say, I'm not sure whether this is a bug report or a feature request. 😅 Should I be able to set them globally? Or was support for that not added intentionally?

Either way, it would be helpful for me to be to able to set those globally, since I don't plan on using per-route rate limiting.

Thanks for your help!

**Comment by mcollina** [comment]
This is not supported yet! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Uzlopak** [comment]
I guess this can be closed then?
