### ISSUE TITLE
would it be possible to add a function for when the number of requests for ban was reached, it would be executed

### ISSUE THREAD

**Issue by DiogoMarques2003** [fastify/fastify-rate-limit#250]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

There is a function to be able to perform some action for when the number of ban requests is reached

### Motivation

I would like this function to be implemented to be able to prohibit ip from making requests to the api

### Example

```js
fastify.register(import('@fastify/rate-limit'), {
  max: 100,
  ban: 10,
  timeWindow: '1 minute',
  onBanReach: (req, key) => {
  // Code to block user
  }
})
```

**Comment by Eomm** [comment]
Do you mean like the `onExceeded` option?

**Comment by DiogoMarques2003** [comment]
> Do you mean like the `onExceeded` option?

Yes, but when the ban limite are reachd and/or exceeded

**Comment by DiogoMarques2003** [comment]
Maybe some function to be called after this line: https://github.com/fastify/fastify-rate-limit/blob/2f9d0fa2d9c3142fcdd7371e14183adcc6bec1fb/index.js#L259

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by DiogoMarques2003** [comment]
https://github.com/fastify/fastify-rate-limit/pull/251
@mcollina can you check if is this pls.
