### ISSUE TITLE
Custom response

### ISSUE THREAD

**Issue by pc-jedi** [fastify/fastify-rate-limit#26]
Currently you will always get a JSON in the following schema if you exceed the rate limit:
```json
{
  "error": "Too Many Requests",
  "message": "Rate limit exceeded, retry in 1 minute",
  "statusCode": 429
}
```

Since I use a different JSON schema in my response, it would be great to have a way of customizing the response. E.g. Having a callback to format/send the response.

**Comment by mcollina** [comment]
Would you like to send a PR? It would be a great feature!

**Comment by saikatharryc** [comment]
@pc-jedi @mcollina  anything on custom response messages?

**Comment by mcollina** [comment]
I’m happy to get a PR for this.

**Comment by saikatharryc** [comment]
@mcollina  can you look at the above PR?
