### ISSUE TITLE
Req.ip or req.raw.ip? Cookies?

### ISSUE THREAD

**Issue by ReTWi** [fastify/fastify-rate-limit#27]
In [docs we have](https://github.com/fastify/fastify-rate-limit):
```
fastify.register(require('fastify-rate-limit'), {
  keyGenerator: function(req) { /* ... */ }, // default (req) => req.ip
})
```

But i had undefined for req.ip. I think it's was changed sometime ago, not sure. Maybe docs should be updated?
```
  keyGenerator: function(req) {
    console.log(req.ip) //undefined
    console.log(req.raw.ip) //ok
    return req.ip 
  }
```

In code i can see:
```
const keyGenerator = typeof opts.keyGenerator === 'function'
    ? opts.keyGenerator
    : (req) => req.raw.ip
```

And a question. If hooks added onRequest, than there is no way rate limit based on parsed cookies (fastify-cookie)?

**Comment by mcollina** [comment]
Can yoo send a PR to update the docs?

I don’t understand you question, can you make an example (ideally with code).

**Comment by ReTWi** [comment]
@mcollina i will. 

If i want to limit based on cookies (user.id), i will need to parse them first, because onRequest hooks have them raw only. But as i already have fastify-cookie pluggin, they parsed by it but will be avaiable only in preHandler (or somewhere near by).

I want to do like this:
```
fastify.register(require('fastify-rate-limit'), {
  keyGenerator: function(req) {
   req.cookies.user_id
})
```

It wood be good to limit authentication attems to.

**Comment by mcollina** [comment]
I think we can make the hook configurable via an option. In Fastify v2 (due in 1-2 weeks at most) `onRequest` has the same signature of prehandler, and a lot of other lifecycle phase. Would you like to send a PR to make your use case possible?
