### ISSUE TITLE
@fastify/rate-limit not compatible with 3.X fastify

### ISSUE THREAD

**Issue by leandrohlsilva** [fastify/fastify-rate-limit#273]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.X

### Plugin version

7.5.0

### Node.js version

16.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

I'm getting the following error when running my Fastify server.

```
FastifyError: fastify-plugin: @fastify/rate-limit - expected '4.x' fastify version, '3.29.0' is installed\n" +
      '    at Object.checkVersion (/path/to/project/node_modules/fastify/lib/pluginUtils.js:107:63)\n' +
      '    at Object.registerPlugin (/path/to/project/node_modules/fastify/lib/pluginUtils.js:121:16)\n' +
      '    at Boot.override (/path/to/project/node_modules/fastify/lib/pluginOverride.js:28:57)\n' +
      '    at Plugin.exec (/path/to/project/node_modules/avvio/plugin.js:80:33)\n' +
      '    at Boot.loadPlugin (/path/to/project/node_modules/avvio/plugin.js:274:10)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
    name: 'FastifyError',
    code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
    message: "fastify-plugin: @fastify/rate-limit - expected '4.x' fastify version, '3.29.0' is installed",
    statusCode: 500
```

The documentation says it should support fastify 2.X - 4.X
Is this possible? Should I use a different version instead?

Thank you!

### Steps to Reproduce

Install fastify 3.29.0 and @fastify/rate-limit 7.5.0

Attempt to run your fastify server.

### Expected Behavior

@fastify/rate-limit should support fastify 3.29.0 as mentioned in the documentation.

**Comment by Uzlopak** [comment]
I assume, that we will update the documentation and not ensure compatibility with fastify 3

**Comment by Eomm** [comment]
It used to: 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/11404065/204022264-e57ee831-dcc1-4931-a10d-263a44013402.png">


https://github.com/fastify/fastify-rate-limit/pull/239/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

> Is this possible? Should I use a different version instead?

Yes, v6 will work
