### ISSUE TITLE
associated apykey in requests

### ISSUE THREAD

**Issue by stefanocudini** [fastify/fastify-rate-limit#280]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

can this plugin be used for requests with a particular _apikey_ passed via get/post params?

what other fastify plugin can be used together with this one to get the result?

**Comment by Uzlopak** [comment]
You could utilize allowList paramater as it also can handle a function were the first parameter is the request and if it returns true it will ignore the rate limit.

**Comment by Eomm** [comment]
> can this plugin be used for requests with a particular apikey passed via get/post params?

Yes, I used to apply the `max` option:

```
fastify.register(rateLimit, {
  /* ... */
  keyGenerator (request) { return request.headers['api-key'] },
  max: async (request, key) => { return key === 'asd-qwe-123' ? 3000000 : 2 }
})
```
