### ISSUE TITLE
allowPaths

### ISSUE THREAD

**Issue by DiogoMarques2003** [fastify/fastify-rate-limit#282]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It's possible add a system like allowList, but for paths in api ?

### Motivation

I want this because one plugin register one route, and on this route I can't have rate limit

### Example

```js
allowPaths: ['/api/docs', '/docs']

allowPaths: (request) => {
 //code
}
```

**Comment by DiogoMarques2003** [comment]
and like if i have '/api/docs/*' in array the system exclude rate limit of all paths started for this

**Comment by gurgunday** [comment]
Just a reminder that you can already register rate-limit to specific routes using Fastify’s encapsulation. It’s not exactly an allowPaths but it works just as well.

**Comment by DiogoMarques2003** [comment]
> Just a reminder that you can already register rate-limit to specific routes using Fastify’s encapsulation. It’s not exactly an allowPaths but it works just as well.

How to do this ? Can you give a example pls ?

**Comment by mcollina** [comment]
```js
const app = fastify()

app.register(async function () {
  app.register(require('@fastify/rate-limit'), {
  })

  // put all the routes to rate limit here
})

app.register(async function () {
  // put all the routes to not rate limit here
})
```

**Comment by DiogoMarques2003** [comment]
I @mcollina I already try this, but this don't work because the route is /api/docs ...

**Comment by mcollina** [comment]
I'm not sure how that prevents you to define /docs inside the other plugin.

**Comment by DiogoMarques2003** [comment]
@mcollina Because in /api/docs I don't want to have ratelimit

**Comment by mcollina** [comment]
This should work:

```js

const app = fastify()

app.register(async function () {
  app.register(require('@fastify/rate-limit'), {
  })

  // put all the routes to rate limit here
})

app.register(async function () {
  // put all the routes to not rate limit here

  app.get('/api/docs', ()=> ...)
})

```

**Comment by DiogoMarques2003** [comment]
Ok, but the /api/docs in one plugin, exists some problem ?

**Comment by mcollina** [comment]
There should not be any problems.

**Comment by DiogoMarques2003** [comment]
Okok, but if I make this feature, will it be accepted?

**Comment by mcollina** [comment]
No, I don't think so.

There is even a better way to declare a route without rate limiting (https://github.com/fastify/fastify-rate-limit/blob/4b78b2efabb9abddc746cc0c88597230157403d1/index.js#L139):

```js
app.get('/', { config: { rateLimit: false } }, () => ...)
```
