### ISSUE TITLE
How to Limit Download Speed in fastify-rate-limit?

### ISSUE THREAD

**Issue by Uriel29** [fastify/fastify-rate-limit#290]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi! 

It is important to limit HTTP bandwidth on your website to prevent a few users from cornering all your downloads and ensure that all users have good user experience.

limit_rate directive allows you to limit download speed in NGINX. You can add it in http, location or server blocks

Here’s an example to limit download speed to 50kb/sec.

`http {
   ...
   limit_rate 50k;
   ...
}`

How to Limit Download Speed fastify-rate-limit? 
For example imagine 2 users (A, B) who respectively want to download files X, and Z. The Server has a total bandwidth of 10MB/s (for demonstration). Users are entitled to 1 MB/s at most (unless the server is maxed, then it's less)

Hugs

**Comment by mcollina** [comment]
This is currently not supported, but it would be an amazing addition.

**Comment by Ekott2006** [comment]
Sorry, can I get more information about this, I would like to work on this issue??

**Comment by mcollina** [comment]
@Ekott2006 go for it!

**Comment by Uzlopak** [comment]
We created a new plugin called @fastify/throttle, which does exactly this ;).
