### ISSUE TITLE
Rate limiter not working at all? Followed documentation.

### ISSUE THREAD

**Issue by Dmitriyx** [fastify/fastify-rate-limit#292]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15

### Plugin version

8.0

### Node.js version

18

### Operating system

MacOS

### Operating system version (i.e. 20.04, 11.3, 10)

Macbook Pro M2 Chip
Ventura 13.0
### Description

Start the server and try to hit the rate limit. Seems like it is not working. I followed the documentation and even made a separate project to test this. 

### Steps to Reproduce

Package JSON:
```
{
  "name": "testapp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fastify/rate-limit": "^8.0.0",
    "fastify": "^4.15.0"
  }
}

```

server.js
```
// Require the framework and instantiate it
const fastify = require('fastify')({ logger: true })

fastify.register(require('@fastify/rate-limit'), {
    global: true,
    max: 1,
    timeWindow: '1 hour',
})

// Declare a route
fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
})

// Run the server!
const start = async () => {
    try {
        await fastify.listen({ port: 3000 })
    } catch (err) {
        fastify.log.error(err)
        process.exit(1)
    }
}
start()
```

### Expected Behavior

exptected to hit rate limit after starting server and spamming GET expoint, but what happens is that I get status code 200.

I tried to tinker with this many times and I do not have any success.

![image](https://user-images.githubusercontent.com/16686549/233752684-dea5f013-d29e-4822-9322-8d885295c1ed.png)
Source: https://github.com/fastify/fastify-rate-limit

**Comment by Eomm** [comment]
Your code on the left is not the same as the doc code on the right.

![image](https://user-images.githubusercontent.com/11404065/233765708-9471df55-439b-4f71-a63e-4df6a3e25c42.png)

A necessary `await` is missing in front of `fastify.register(plugin)`

**Comment by Dmitriyx** [comment]
thanks for the quick response.
I thought perhaps it would still work since the routes registered correctly ( in my other project ).
I will test with top level await and have an update here.

**Comment by Dmitriyx** [comment]
works! thanks for the help
