### ISSUE TITLE
Weird ES8 module imports

### ISSUE THREAD

**Issue by UtkarshVerma** [fastify/fastify-rate-limit#297]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

8.0.0

### Node.js version

20.2.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch Linux

### Description

The only way I can import this module in my ES8 codebase is as follows:

### Steps to Reproduce

```
import fastifyRateLimitModule from "@fastify/rate-limit";
const fastifyRateLimit = fastifyRateLimitModule.default;
```

### Expected Behavior

I expect it to be imported normally like other plugins:
```
import fastifyRateLimit from "@fastify/rate-limit";
```

**Comment by mcollina** [comment]
it works like other plugins, could you create a small repo to reproduce your problem?

**Comment by andrewshawcare** [comment]
Yeah, it seems to be the same issue that was experienced in AJV: https://github.com/ajv-validator/ajv/issues/1381

I have to do the following to register the plugin correctly:

```typescript
import Fastify from "fastify";
import fastifyRateLimit from "@fastify/rate-limit";

const fastify = Fastify();

// Does not compile, get a, "No overload matches this call" error.
fastify.register(fastifyRateLimit);

// This works
fastify.register(fastifyRateLimit.default)
```

**Comment by andrewshawcare** [comment]
I can write the former with fastifyCors just fine but not with fastifyRateLimit:

```typescript
import Fastify from "fastify";
import fastifyCors from "@fastify/cors";

const fastify = Fastify();

// This works
fastify.register(fastifyCors)
```

**Comment by andrewshawcare** [comment]
It should also be noted that this is using `"type": "module"` in `package.json`.

**Comment by andrewshawcare** [comment]
It looks like the difference between `@fastify/cors` and `@fastify/rate-limit` is how they handle the export.

`@fastify/cors` has a namespace and a function declaration named `fastifyCors` and does not make the `fastifyCors` export a default export.

`@fastify/rate-limit` declares a `FastifyPluginCallback<RateLimitPluginOptions>` default export.

The comment referenced above describes how the `@fastify/rate-limit` approach might not be valid Javascript and I'm sure there may be some combination of `module`, `moduleResolution`, `target`, or other options that would potentially get this to compile, just not sure what they are (new to Typescript myself).

**Comment by Eomm** [comment]
It is not clear to me: are you using TypeScript?

**Comment by andrewshawcare** [comment]
My apologies. I am using Typescript. I am not sure if the original poster is. I can create a separate issue if it is not the case for the original poster.

**Comment by UtkarshVerma** [comment]
I am also using Typescript. Will create a small example project reproducing this once I'm back.

**Comment by Shyam-Chen** [comment]
I am using TypeScript with Vite, and it works fine.

```ts
import rateLimit from '@fastify/rate-limit';

app.register(rateLimit, { max: 3, timeWindow: 5000 });
```

![image](https://github.com/fastify/fastify-rate-limit/assets/13535256/ce123c26-fc4e-473b-a413-926e7d2d7590)

**Comment by UtkarshVerma** [comment]
I have created a minimal reproducible example at https://github.com/UtkarshVerma/fastify-demo.

**Comment by Shyam-Chen** [comment]
> I have created a minimal reproducible example at https://github.com/UtkarshVerma/fastify-demo.

```ts
import fastify from 'fastify';
import rateLimit from '@fastify/rate-limit';

const app = () => {
  const app = fastify();

  app.register(rateLimit, { max: 3, timeWindow: 5000 });

  app.get('/', async () => {
    return { hello: 'world' };
  });

  return app;
};

const server = app();

const start = async () => {
  try {
    await server.listen({ host: '127.0.0.1', port: 3000 });
  } catch (err) {
    server.log.error(err);
    process.exit(1);
  }
};

start();
```

**Comment by Fdawgs** [comment]
> Yeah, it seems to be the same issue that was experienced in AJV: [ajv-validator/ajv#1381 (comment)](https://github.com/ajv-validator/ajv/issues/1381#issuecomment-756635396)
> 
> I have to do the following to register the plugin correctly:
> 
> ```ts
> import Fastify from "fastify";
> import fastifyRateLimit from "@fastify/rate-limit";
> 
> const fastify = Fastify();
> 
> // Does not compile, get a, "No overload matches this call" error.
> fastify.register(fastifyRateLimit);
> 
> // This works
> fastify.register(fastifyRateLimit.default)
> ```

Just commenting to confirm I can recreate this:




```
No overload matches this call.

  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof import("c:/git-repos/applications/test-repo/node_modules/@fastify/rate-limit/types/index")' is not assignable to parameter of type 'FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>'.
      Type 'typeof import("c:/git-repos/applications/test-repo/node_modules/@fastify/rate-limit/types/index")' provides no match for the signature '(instance: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProvider>, opts: FastifyPluginOptions, done: (err?: Error | undefined) => void): void'.

  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof import("c:/git-repos/applications/test-repo/node_modules/@fastify/rate-limit/types/index")' is not assignable to parameter of type 'FastifyPluginAsync<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger>'.
      Type 'typeof import("c:/git-repos/applications/test-repo/node_modules/@fastify/rate-limit/types/index")' provides no match for the signature '(instance: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProvider>, opts: FastifyPluginOptions): Promise<...>'.

  Overload 3 of 3, '(plugin: FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof import("c:/git-repos/applications/test-repo/node_modules/@fastify/rate-limit/types/index")' is not assignable to parameter of type 'FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProvider, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>'.
```

**Comment by Uzlopak** [comment]
@Fdawgs 
Despite that you can recreate... you are using windows?

**Comment by Shyam-Chen** [comment]
Do you want to remove `{ "type": "module" }` in the `package.json` file?

**Comment by andrewshawcare** [comment]
> Do you want to remove `{ "type": "module" }` in the `package.json` file?

@Shyam-Chen are you intending to say that, when you removed it, you were able to run the example? If so, then that would be the a condition for the bug (i.e. that module-typed packages cannot import this Fastify plugin).

**Comment by Shyam-Chen** [comment]
> > Do you want to remove `{ "type": "module" }` in the `package.json` file?
> 
> @Shyam-Chen are you intending to say that, when you removed it, you were able to run the example? If so, then that would be the a condition for the bug (i.e. that module-typed packages cannot import this Fastify plugin).

1. `"moduleResolution": "node"`  in `tsconfig.json`
2. change to `dist/index.mjs`

**Comment by dev101** [comment]
`"moduleResolution": "node"` does the trick, but that's doesn't help as I want my code to be Pure ESM.

Actually, [declaration in the root folder](https://github.com/fastify/fastify-rate-limit/blob/master/index.d.ts) would work properly, I wonder why both `index.d.ts` and `types/index.d.ts` coexist?

The former would work with both `"moduleResolution": "Node"` and `"moduleResolution": "Node16"`.

I would suggest this [simple fix](https://github.com/fastify/fastify-rate-limit/pull/302) (similar to what is done in @fastify/mongodb and @fastify/cors), though you maybe have [something else in mind](https://github.com/fastify/fastify-rate-limit/pull/276).

**Comment by Uzlopak** [comment]
Oha. The index.d.ts in the root has to be deleted.
