### ISSUE TITLE
Incorrect Retry-After header value

### ISSUE THREAD

**Issue by awlayton** [fastify/fastify-rate-limit#301]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

8.0.0

### Node.js version

20.2.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.2

### Description

It seems the value of the Retry-After header is expressed in milliseconds instead of seconds (or an http-date) as specified by [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-retry-after).

### Steps to Reproduce

`@fastify/rate-limit` options:
```typescript
const options = {
  max: 5,
  timeWindow: '1 minute',
};
```

Headers on 429 response:
```http
x-ratelimit-limit: 5
x-ratelimit-remaining: 0
x-ratelimit-reset: 58
retry-after: 60000
```

### Expected Behavior

The value of `Retry-After` should be `60` (i.e., 1 minute in seconds), not `60000`.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Uzlopak** [comment]
Probably issue is here

https://github.com/fastify/fastify-rate-limit/blob/6bf150ad2b0fe7104eb8074316867ea857462ee9/index.js#L249

timeWindow is time in milliseconds but we should have a timeWindowInSeconds value were we have the timeWindow in seconds and use that.

**Comment by Uzlopak** [comment]
Created a PR #307
