### ISSUE TITLE
Wrong type for rateLimit: false

### ISSUE THREAD

**Issue by Cluster2a** [fastify/fastify-rate-limit#309]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

 4.19.2

### Plugin version

8.0.3

### Node.js version

20.3.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 23.04

### Description

Hey, there seems to be an issue with the type:
```JS
server.get(
	'/status',
	{
		config: {
			rateLimit: false
		}
	},
	(req, reply) => {
		reply.send();
	}
);
```
This results in the following error:

![image](https://github.com/fastify/fastify-rate-limit/assets/84905165/55520b41-d023-40e0-87bf-da2797053c44)

### Steps to Reproduce

- add a route with the rateLimit = false-option

### Expected Behavior

Should work as documented in the docs:
```JS
// this route doesn't have any rate limit
fastify.get('/public', {
  config: {
    rateLimit: false
  }
}, (request, reply) => {
  reply.send({ hello: 'from ... public' })
})
```

**Comment by Cluster2a** [comment]
@Uzlopak, is there going to be a new release with the fix?

**Comment by Uzlopak** [comment]
@eomm
@mcollina
