### ISSUE TITLE
Rate limit don't working even using async/await

### ISSUE THREAD

**Issue by Snarloff** [fastify/fastify-rate-limit#362]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.0

### Plugin version

9.1.0

### Node.js version

20

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

23H2

### Description

Hello. I tried several ways to use the package, but in none of them the package is working for me. It does not assign headers to the request and does not block excessive requests.

## Source Code

![image](https://github.com/fastify/fastify-rate-limit/assets/46792575/444492ff-a9dd-4c79-ae23-09fcd3da24f6)

**Comment by Eomm** [comment]
`await plugins()` must be run before adding routes.

It seems your app does not have routes between:

```
// do not add routes here

await plugins();

// add routes here

await app.listen()
```

**Comment by Snarloff** [comment]
> `await plugins()` must be run before adding routes.
> 
> It seems your app does not have routes between:
> 
> ```
> // do not add routes here
> 
> await plugins();
> 
> // add routes here
> 
> await app.listen()
> ```

![image](https://github.com/fastify/fastify-rate-limit/assets/46792575/0e7a16e3-29e8-4d34-a29e-f0d8105f65f4)

Nothing happens :/

**Comment by Snarloff** [comment]
> `await plugins()` must be run before adding routes.
> 
> It seems your app does not have routes between:
> 
> ```
> // do not add routes here
> 
> await plugins();
> 
> // add routes here
> 
> await app.listen()
> ```

Thanks!
