### ISSUE TITLE
Cannot find module 'ioredis' during TS compile

### ISSUE THREAD

**Issue by fox1t** [fastify/fastify-rate-limit#37]
Hi, i just updated to 2.1.1 and got this error during TS compilation.
It happens because `ioredis` is in devDependencies and you are using it in index.d.ts, that is just a typings file.
Let me know if you need help.

**Comment by mcollina** [comment]
Would you mind sending a pr to remove `ioredis` from `index.d.ts`?

**Comment by fox1t** [comment]
What about using [@types/ioredis](https://www.npmjs.com/package/@types/ioredis) as dependency?

**Comment by mcollina** [comment]
I'm -1 in adding any `@types/ioredis` as dependencies. They increase the download size for everybody, and they are not often greatly maintained.

**Comment by fox1t** [comment]
Then we must use `redis: any`. I'll open a PR.
