### ISSUE TITLE
Reach 100% test coverage

### ISSUE THREAD

**Issue by gurgunday** [fastify/fastify-rate-limit#371]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We want to remove:

https://github.com/fastify/fastify-rate-limit/blob/595a627020837d5c4ad3de7a235f385f3e6af2a5/.taprc#L3-L6

**Comment by jean-michelet** [comment]
I have a lot of failures locally: Ubuntu 22, Node 22

![summary](https://github.com/fastify/fastify-rate-limit/assets/110341611/9eef8e9e-d1ab-426d-9c2a-6a92a72d0cd9)

**Comment by gurgunday** [comment]
It's because you need a running redis instance on your machine

https://github.com/fastify/fastify-rate-limit/blob/595a627020837d5c4ad3de7a235f385f3e6af2a5/.github/workflows/ci.yml#L18C47-L18C49

You can use Docker to set one up, or use Actions/CI on your local repo to test the changes
