### ISSUE TITLE
Can it support bandwidth limit?

### ISSUE THREAD

**Issue by seepine** [fastify/fastify-rate-limit#386]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Example 
```js
options = {
  maxBandwidth: '1M'    // every request the max bandwidth must be < 1M/s
  globalMaxBandwidth: '10M'  // all request the max bandwidth sum must be < 10M/s
}
```
Or
request header `x-bandwidth-limit-key: uuidA` and
```js
options = {
  maxBandwidth: {
    uuidA: '1M'    // match the request header
  },
  globalMaxBandwidth: {
    uuidA: '10M'    // match the request header
  }
}
```

### Motivation

I code the network ingress and WAF base fastify, the bandwidth limit are important.

**Comment by Uzlopak** [comment]
You maybe want to look at https://github.com/fastify/fastify-throttle
