### ISSUE TITLE
Per route limit not working

### ISSUE THREAD

**Issue by Tobjoern** [fastify/fastify-rate-limit#39]
In my project I tried using the rate-limit, and it worked. Then I tried using the per-route limit, but it didn't work at all. I replicated the example to see if I made any error in my project, but it still didn't work.

Here is the code I used:
```
const fastify = require('fastify')()

fastify.register(require('fastify-rate-limit'),
  {
    global: false,
    max: 10,
    timeWindow: '1 minute',
    skipOnError: false,
    keyGenerator: function(req) {
        console.log(req.ip);
        return req.ip;
    }
  })

fastify.get('/rate-test', {
  config: {
    rateLimit: {
      max: 3,
      timeWindow: '1 minute'
    }
  }
}, (req, reply) => {
  reply.send({ hello: 'from ... root' })
});

fastify.listen(3000, err => {
    if (err) throw err
    console.log('Server listening at http://localhost:3000')
})
```

The server returns a 429 status only after 10 continuous requests, but not after 3.

**Comment by Eomm** [comment]
@Tobjoern could you try without the `config` field?

Like this:
```
fastify.get('/rate-test', {
    rateLimit: {
      max: 3,
      timeWindow: '1 minute'
    }
}, (req, reply) => {
  reply.send({ hello: 'from ... root' })
});
```

**Comment by Tobjoern** [comment]
> EDIT: the feature has not been released

Hm okay, this wasn't obvious in the documentation. Any ideas when it will be out?

**Comment by Eomm** [comment]
I checked it yesterday, I think a week (+-) should be enough 👍
