### ISSUE TITLE
Dynamic max requests

### ISSUE THREAD

**Issue by ziglef** [fastify/fastify-rate-limit#43]
I was looking at the code and it seems that the plugin allows for the specified `max` option to be a function, but when I try to use a function to generate the max value I get an error such as:

> unhandled exception TypeError: The header content contains invalid characters
> at storeHeader (_http_outgoing.js:436:13)
> at ServerResponse._storeHeader (_http_outgoing.js:350:7)
> at ServerResponse.writeHead (_http_server.js:257:8)
> at onSendEnd (/usr/src/app/node_modules/fastify/lib/reply.js:329:7)
> at onSendHook (/usr/src/app/node_modules/fastify/lib/reply.js:282:5)
> at _Reply.Reply.send (/usr/src/app/node_modules/fastify/lib/reply.js:139:3)
> at onIncr (/usr/src/app/node_modules/fastify-rate-limit/index.js:136:12)
> at LocalStore.incr (/usr/src/app/node_modules/fastify-rate-limit/store/LocalStore.js:19:3)
> at Object.preHandler (/usr/src/app/node_modules/fastify-rate-limit/index.js:110:27)
> at hookIterator (/usr/src/app/node_modules/fastify/lib/hooks.js:124:10)

Is there support for a non-static max requests value and I'm missing something or is this not implemented?

In my use case different clients connecting to the API have different max limits and as such I would like to make the max option depend on a function provided by me that would return a value to be checked against.

Thanks for your time!

**Comment by Eomm** [comment]
Oh, it could be an error because max must be a number in other parts of code.

The max value dynamic could be a good feature, we should think a list of use cases because if it changes in the time frame what we want to do?

The max is dynamic on startup or per each request?

Do you have already think cases?

**Comment by ziglef** [comment]
I have a use case I was trying to use it for.

Currently on an API I'm developing I use this to do a global rate limit on the number of requests. Now I wanted to add a rate limit that would vary from user to user.

The use case is that we have multiple "clients" that pay for different amounts of transaction limits, and I would like to enforce it with something like this.

My idea was to have an object in Redis that I fetch using an unique identifier and that object would contain the key for that user as well as that user's max limit.

So I guess a function that would generate a different limit with every request would be my use case

**Comment by mcollina** [comment]
@ziglef would you like to send a PR?
