### ISSUE TITLE
Per route limit with redis *and* pre-handler does not work

### ISSUE THREAD

**Issue by amir-hadi** [fastify/fastify-rate-limit#47]
## 🐛 Bug Report

When you are using Redis *and* a custom pre handler in a route, then the rate limiting basically fails.

## To Reproduce

1. Create a route
2. Create a pre handler method for that route
3. Configure rate limiting via `config`
4. Fail

Paste your code here:

https://github.com/amir-hadi/fastify-rate-limit/blob/master/test/route-rate-limit.test.js

I forked this repo and added another test case that proves that something is wrong with Redis and a pre handler on the route. Please see the test case in my repo that is failing.

## Expected behavior
It should also work with Redis and a pre handler.

## Your Environment

- *node version*: 10.16
- *fastify version*: >=2.5.0
- *os*: Mac
- *any other relevant information*

Any help would be much appreciated. It looks in your preHandler the callback does not wait long enough before calling next. So your pre handler is exiting/returning and your callback is not modifying the response anymore.

**Comment by mcollina** [comment]
Would you like to send a PR with a fix? You seemed to have researched the issue in full.

**Comment by amir-hadi** [comment]
Hey @mcollina,

we found the bug and proofed it with a test case, but I don't know how fastify works or is supposed to work. My first guess would be that we need to wait for the `onIncr` callback to finish before we can get out of the handler. Would that be correct?

**Comment by mcollina** [comment]
I'd say open a PR and we'll be happy to review. Adding a unit test for this case would help.

**Comment by Eomm** [comment]
I don't understand the problem: what do you expect? The custom `preHandler` should not be called?

If so, the code says that we attach the rate limit after the route preHandler:

https://github.com/fastify/fastify-rate-limit/blob/92c84b04c4967682df4877a93ad7d9d29682ca9c/index.js#L100

**Comment by amir-hadi** [comment]
Hello,

sorry that I didn't close this one yet. It works as intended. Our preHandler was implemented wrong, we had an async function, but did call the preHandler manually. Apparently you don't need to do this in fastify.
