### ISSUE TITLE
Can't apply whitelist per route

### ISSUE THREAD

**Issue by mariamgarchagudashvili** [fastify/fastify-rate-limit#49]
Trying to whitelist some keys per route but it does not apply. 

## To Reproduce

Steps to reproduce the behavior: Add rate limit config to the route and add whitelist param.

```js
server.register(rateLimitPlugin, {
  global : false,
  redis,
  skipOnError: true
});
 server.get('/test', {
    preHandler: authHandler,
    config: {
      rateLimit: {
        max: 3,
        timeWindow: '1 minute',
        whitelist: ['testuser'],
        keyGenerator: function (req: any) {
          return req.params.authedUserId || test;
        },
        onExceeded: function (req: any) {
          console.log('Exceeded')
        },
      }
    }
  }, handler);
```

## Expected behavior

As documentation shows, it should allow to add whitelist list per route not only on global.
I think problem is in preHandler
```js
    // whitelist doesn't apply any rate limit
    if (pluginComponent.whitelist.indexOf(key) > -1) {
      next()
      return
    }
```
`pluginComponent.whitelist ` is an empty array. Should be `params.whitelist` in this case.
## Your Environment

- *node version*: 10.16
- *fastify version*: >=2.5

**Comment by mcollina** [comment]
Would you like the send a PR to fix that?

**Comment by mariamgarchagudashvili** [comment]
I will give a shot

**Comment by RafaelGSS** [comment]
@mariamgarchagudashvili can provide a full code example? I'll attach this issue
