### ISSUE TITLE
No rate limiting on not-found/undefined routes

### ISSUE THREAD

**Issue by ddsultan** [fastify/fastify-rate-limit#59]
## 🐛 Bug Report

Even if the clients (based on their ip) has done too many request in the given timeWindow, the server does not respond with `429`. This makes the application still vulnerable to attacks

## To Reproduce

1. JS

```js
const fastify = require('fastify')()

fastify.register(require('fastify-rate-limit'), {
  max: 2,
  timeWindow: '1 minute'
})

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log('Server listening at http://localhost:3000')
})
```
2. Curl
```bash
 curl 'http://localhost:8080/foo'
```

## Expected behavior

It should give `429`, "Too Many Requests", response, but giving this:

```json
{ 
    "statusCode":404,
    "error":"Not Found",
    "message":"Not Found"
}

```

**Comment by Eomm** [comment]
You didn't register the /foo route

404 is faster than rate limit (that ask to redis the counter) so why do you think to be vulnerable?

**Comment by bradenhs** [comment]
Sometimes you want to artificially slow down a client that is making too many requests. If there is some naive integration with your platform that has a bug in it and is hitting some no longer existing route and retrying on failure, it could be helpful to detect that and artificially make requests take longer to complete to ease the strain on your platform.

**Comment by mcollina** [comment]
In that case it's quite deliberate and I'd recommend to define a route that returns a 404 or 429 manually.

**Comment by Eomm** [comment]
> Sometimes you want to artificially slow down a client that is making too many requests. If there is some naive integration with your platform that has a bug in it and is hitting some no longer existing route and retrying on failure, it could be helpful to detect that and artificially make requests take longer to complete to ease the strain on your platform.

As a hint on how to do that if you have the chance to add this feature:

- create a request decorator that execute the rate limit with global configuration
- in the `setNotFoundHandler` run the `await request.rateLimit()`

This would need a little refactor of this plugin but all the functions are already in place I think
