### ISSUE TITLE
Feature: Ability to pass in a custom Store

### ISSUE THREAD

**Issue by Svjard** [fastify/fastify-rate-limit#67]
## 🚀 Feature Proposal

Be a nice enhancement to add the ability to pass in a Store interface which abides by the current constructs of Local/Redis store, i.e. incr method and callback. Easy way to extend for other storage mechanisms without bloating the existing package. 

## Motivation

There are a lot of memory storage tools out there, as well as traditional ones such as databases, so often adding a new technology into an already established stack can be costly in terms of maintenance, hosting, etc...

## Example

function thestore = function(timeWindow, key) {

}
etc...

fastify.register(require('fastify-rate-limit'), {
  store: require('./my-custom-store')
})

This means a slightly custom call to the custom-store but otherwise should be a very doable feature.

**Comment by mcollina** [comment]
Seems fair! Would you like to send a PR?

**Comment by Svjard** [comment]
I'll work on a PR for it this week unless someone else beats me to it. :+1:

**Comment by Eomm** [comment]
Merged with #68
