### ISSUE TITLE
Consider not using X-Forwarded-For header for detecting the IP address

### ISSUE THREAD

**Issue by mcibique** [fastify/fastify-rate-limit#7]
I tried to use this rate limiter with fastify server behind the proxy and I found two major problems with the detection of the IP address in following code:

```js
var ip = req.headers['X-Forwarded-For'] || req.connection.remoteAddress
```

1. All keys in `req.headers` are in lowercase so the `req.headers['X-Forwarded-For']` is always undefined even if the proxy sends the header to the upstream. That means, `req.connection.remoteAddress` is always used as IP and it's always the same value (the IP of the proxy). This gives an attacker a possibility to make the entire server unavailable for every user.

2. Even if you fix the casing, there is still another issue: You should never use HTTP header as a cache key unless you trust the source. `X-Forwarded-For` header can be crafted on the client. Imagine your fastify server is publicly available (no proxy in front of it), then following requests from the same client are going to be considered as different:

```
$ curl -v -H "X-Forwarded-For: a" http://example.com/
X-RateLimit-Limit: 5
X-RateLimit-Remaining: 4

$ curl -v -H "X-Forwarded-For: b" http://example.com/
X-RateLimit-Limit: 5
X-RateLimit-Remaining: 4

$ curl -v -H "X-Forwarded-For: c" http://example.com/
X-RateLimit-Limit: 5
X-RateLimit-Remaining: 4
```

With this you can bypass the entire rate limiter, by varying the X-Forwarded-For header for each request. The same happens with the proxy in front of it, because proxies usually leave the original `X-Forwarded-For` header and just append its own IP to the end of the string.

There are few candidates which might suit better for the cache key: e.g. nginx adds [X-Real-IP header](https://nginx.org/en/docs/http/ngx_http_realip_module.html) which is always overridden, or you can use a session ID.

I'd like to propose possible solution: use only `req.connection.remoteAddress` by default and provide a configurable option for cases when devs want to change the IP detection behavior: 
```js
fastify.register(require('fastify-rate-limit'), {
  max: 5,
  timeWindow: '1 minute',
  resolveIpAddress: function (req) {
	return req.headers['x-forwarded-for'];
	// or return req.headers['x-real-ip'];
	// or return req.session.id;
  }
});
```
And then the implementation:
```js
var ip;
if (typeof opts.resolveIpAddress === "function") {
	ip = opts.resolveIpAddress(req);
}
if (!ip) {
	ip = req.connection.remoteAddress;
}
```
I can create a PR but first I'd like to hear your opinion.

**Comment by matth-c3** [comment]
I know it's old but why don't you set the rate limit directly on nginx or haproxy ? What do you gain by doing it on the http server directly ? 

sorry if that's stupid question

**Comment by Eomm** [comment]
This is a rightful question but a bit offtopic, please, feel free to open a new issue in case of any other doubts.

To replay to you: there are cases where you haven't an nginx or a haproxy, or I think that the main reason could be **control** because you can apply a specific rate limit per customer for example (more money, more speed 💵)
