### ISSUE TITLE
LocalStore onClose does not calls done after clearInterval

### ISSUE THREAD

**Issue by samaysar** [fastify/fastify-rate-limit#71]
When using fastify-rate-limit with LocalStore, in a NestFastifyApplication instance:

await app.close() hangs forever as localStore in the onClose hook,does not call done=>

app. addHook('onClose', (done) => {
    clearInterval(this.interval);
    // missing done();
})

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by samaysar** [comment]
Hi,
Sure. Let me prepare it... Will send it you by tomorrow.
Thanks for quick response.

Best,

**Comment by samaysar** [comment]
hi Matteo, for your review and release. Thanks.

**Comment by Eomm** [comment]
Released in 3.0.1
Thanks for the contribution 💪

**Comment by samaysar** [comment]
With pleasure.
